services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    data_collector.onethinkorm:
        class: OneThink\OrmBundle\DataCollector\OneThinkOrmCollector
        tags:
            -
                name: data_collector
                template: '@OneThinkOrm\data_collector/one_think_orm.html.twig'
                public: false
                # must match the value returned by the getName() method
                id: 'onethinkorm'
                # optional priority
                priority: 251
    OneThink\OrmBundle\Command\MakeModelCommand:
        tags:
            - { name: 'console.command', command: 'onethink:make:model'}
    OneThink\OrmBundle\EventListener\ResponseListener:
        tags:
            - {name: kernel.event_listener, event: kernel.response}
